version: "3.8"

volumes:
  local-nest-chat-data:
  local-redis-chat-data:

services:
  db:
    image: mongo:4.2.14-bionic
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat
      MONGO_INITDB_DATABASE: chat
    volumes:
      - local-nest-chat-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: chat
      ME_CONFIG_MONGODB_ADMINPASSWORD: chat
    depends_on:
      - db

  redis:
    image: redis:6.2.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - local-redis-chat-data:/data
    command: ["redis-server", "--bind", "redis", "--port", "6379", "--appendonly", "yes"]
