version: "3.8"

volumes:
  local-nest-chat-data:

services:
  db:
    image: mongo:4.2.14-bionic
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat
      MONGO_INITDB_DATABASE: chat
    volumes:
      - local-nest-chat-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: chat
      ME_CONFIG_MONGODB_ADMINPASSWORD: chat
    depends_on:
      - db
