server:
  port: 5000

graphql:
  debug: true
  playground: true
  introspection: true
  autoSchemaFile: _schema.graphql
  dateScalarMode: isoDate
  depthLimit: 10

jwt:
  secret: FLfgscuaISmy39BJ5n5ru8

db:
  uri: mongodb://chat:chat@localhost:27017/admin

redis:
  host: localhost
  port: 6379
