server:
  port: 5000

graphql:
  debug: true
  playground: true
  introspection: true
  autoSchemaFile: _schema.graphql
  dateScalarMode: isoDate
  depthLimit: 10

jwt:
  secret: FLfgscuaISmy39BJ5n5ru8
